<?php
declare(strict_types=1);

namespace Dusan\PhpMvc\Validation\Fluent;


class IntegerFluentValidator extends NumericFluentValidator
{
    protected $type = 'int';

    /**
     * @param int    $start
     * @param int    $end
     * @param string $message
     *
     * @return \Dusan\PhpMvc\Validation\Fluent\NumericFluentValidator
     */
    public function between(int $start, int $end, string $message = 'Number must be between %d and %d')
        : NumericFluentValidator
    {
        return parent::between($start, $end, $message); // TODO: Change the autogenerated stub
    }

    /**
     * @param int    $start
     * @param int    $end
     * @param string $message
     *
     * @return \Dusan\PhpMvc\Validation\Fluent\NumericFluentValidator
     */
    public function betweenIncluding(int $start, int $end, string $message = 'Number must be between %d and %d')
        : NumericFluentValidator
    {
        return parent::betweenIncluding($start, $end, $message); // TODO: Change the autogenerated stub
    }

    /**
     * @param int    $min
     * @param string $message
     *
     * @return \Dusan\PhpMvc\Validation\Fluent\NumericFluentValidator
     */
    public function min(int $min, string $message = 'Number must be minimum %d')
        : NumericFluentValidator
    {
        return parent::min($min, $message); // TODO: Change the autogenerated stub
    }

    /**
     * @param int    $min
     * @param string $message
     *
     * @return NumericFluentValidator
     */
    public function minIncluding(int $min, string $message = 'Number must be minimum %d')
        : NumericFluentValidator
    {
        return parent::minIncluding($min, $message); // TODO: Change the autogenerated stub
    }

    /**
     * @param int    $max
     * @param string $message
     *
     * @return NumericFluentValidator
     */
    public function max(int $max, string $message = 'Number must not exceed %d')
        : NumericFluentValidator
    {
        return parent::max($max, $message); // TODO: Change the autogenerated stub
    }

    /**
     * @param int    $max
     * @param string $message
     *
     * @return NumericFluentValidator
     */
    public function maxIncluding(int $max, string $message = 'Number must not exceed %d')
        : NumericFluentValidator
    {
        return parent::maxIncluding($max, $message); // TODO: Change the autogenerated stub
    }

}
